# Generated by Django 5.2.8 on 2025-11-18 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(db_index=True, max_length=100, unique=True)),
                ('vfile_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('vfile_timestamp', models.BigIntegerField()),
                ('vfile_signature', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('redirect_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_access', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'hosted_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
