# Generated by Django 5.2.8 on 2025-11-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostedfile',
            name='file_path',
        ),
        migrations.AddField(
            model_name='hostedfile',
            name='file_content',
            field=models.TextField(default=''),
        ),
    ]
